### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by sorrowsss** [patil-vipul/VideoCall_PeerJS#2]
hello, your youtube video and this project has been very helpful but i want to know how you can implement screen sharing with this project, i tried looking on google but did not make it work, i would appreciate if you spare the time to add it to this project

**Comment by patil-vipul** [comment]
Sure

**Comment by sorrowsss** [comment]
thank you so much, i am excited to see it

**Comment by sorrowsss** [comment]
i am sorry but how long its going to take before you implant it ?

**Comment by patil-vipul** [comment]
Ohh, I forgot about it due to some work. I'll try to complete it by tonight.

**Comment by sorrowsss** [comment]
thank you, sorry to pressure you , i will  be waiting for it

**Comment by sorrowsss** [comment]
did you make it yet ?, if you did not or can't, send me resource to learn how to do it because i need it urgently please, thank you

**Comment by patil-vipul** [comment]
I'm doing it now. Was going to sleep but your comment struck. : )

**Comment by patil-vipul** [comment]
I've added screen sharing to it.  Please check it. To my surprise its UI is very old (why did I build something like that 😄 ). I'll update it later. 👍

**Comment by patil-vipul** [comment]
> did you make it yet ?, if you did not or can't, send me resource to learn how to do it because i need it urgently please, thank you

Have you checked it. What you think about it?
